name: my-project-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - streamlit
  - pip:
    - pyspark==3.5.5  # Spark
    - debugpy         # Debugging
    - jupyter         # Notebooks
    - sphinx          # Documentation
    - black           # Code formatting