name: spark-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pyspark=3.5.5   # Spark
  - pip:
    - debugpy       # Debugging
    - jupyter       # Notebooks
    - sphinx        # Documentation