services:
  pyspark-project:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    image: pyspark-project
    container_name: pyspark-project
    working_dir: /my-project-dir
    ports:
      - "8501:8501" # Streamlit
      - "5678:5678" # Debugging
      - "8888:8888" # Jupyter-Notebook
      - "4040:4040" # SparkUI,
    volumes:
      - ../:/my-project-dir
    environment:
      # For debugging
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/my-project-dir
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_SERVER_ADDRESS=0.0.0.0
      - DEBUG=true
    
    command: tail -f /dev/null 